name: Auto database update browser-country
on:
  schedule:
    - cron: '42 19 * * *'
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
jobs:
  release:
    name: Auto database update browser-country
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - name: install dependencies
        run: npm i
      - name: update
        run: npm run updatedb-browser-country
      - name: test
        run: npm run test
      - name: commit
        run: script/auto-update-country.sh
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GTOKEN}}
